accounts/urls.py
from django.urls import path
# from django.contrib.auth import views as auth_views
from accounts import views
# from django.contrib.auth.views import (
#     login, logout, password_reset,
#     password_reset_done,
#     password_reset_confirm,
#     password_reset_complete
# )

from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
app_name = 'accounts'
urlpatterns = [
    path('', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout', LogoutView.as_view(template_name= 'accounts/logout.html'), name='logout'),
    path('register/', views.RegisterView, name='register'),
    path('profile/',views.profile_view,name='profile_view'),
    path('profile/edit/',views.edit_profile,name='edit_profile'),
    path('change-password/', views.change_password, name='change_password'),

]

quanly/urls.py
from django.urls import path, include
from quanly.views import AjaxStationDetailView, ManagerView, LanguageView

app_name = 'manager'

urlpatterns = [
    path('',ManagerView.as_view(), name ='manager'),
    path('ajax_station_detail/<int:pk>/', AjaxStationDetailView.as_view()),
    # path('language/', LanguageView.as_view(),name ='language'),
]

sim/urls.py
from django.urls import path
from sim import views
from sim.views import (
    SimView,
    SimListView,
    InsertControl,
    TestView,
    DeleteTestView,
    ChartView,
    DeleteTramView, ModbusView)

app_name = 'sim'

urlpatterns = [
    path('',SimView.as_view(), name ='sim'),
    path('m',ModbusView.as_view(),name = 'modbus'),
    path('sl/',SimListView.as_view(), name ='sim_list'),
    path('control/',InsertControl.as_view()),
    path('test/',TestView.as_view()),
    path('delete/test',DeleteTestView),
    path('delete/tram',DeleteTramView),
    # path('delete/tram',DeleteTramView),
    # path('chart1/',ticket_class_view),
    # path('chart', 'chartFishPrice', name='chartFishPrice'),
]

station/urls.py
from django.urls import path
from station.views import (
    StationView, ControlView, ReportView,
    MapView,HealthyView,AlarmView,
    ParameterView, ModbusView,AccountView,
    GroupView,CreateView,GroupListView,TeView,LanguageView
)
    # , ControlView, StationView ,ReportView
# from station.views.station_view import StationView
# from station.views.parameter_view import ParameterView
# from station.views.modbus_view import  ModbusView

app_name = 'station'

urlpatterns = [
    path('<int:pk>/giam-sat/', StationView.as_view(),name ='giam-sat'),
    path('<int:pk>/bao-cao/',ReportView.as_view(),name ='bao-cao'),
    path('<int:pk>/dieu-khien/',ControlView.as_view(),name ='dieu-khien'),
    path('<int:pk>/ban-do/',MapView.as_view(),name ='ban-do'),
    path('<int:pk>/suc-khoe/',HealthyView.as_view(),name ='suc-khoe'),
    path('<int:pk>/canh-bao/',AlarmView.as_view(),name ='canh-bao'),
    path('<int:pk>/parameter/',ParameterView.as_view(),name ='parameter'),
    path('<int:pk>/modbus/', ModbusView.as_view(),name ='modbus'),
    path('<int:pk>/account/', AccountView.as_view(),name ='tai-khoan'),
    path('<int:pk>/account/group/', GroupView.as_view(),name ='group'),
    path('<int:pk>/account/group/list', GroupListView.as_view(),name ='group-list'),
    path('<int:pk>/account/create/', CreateView.as_view(),name ='create'),
    path('<int:pk>/language/', LanguageView.as_view(),name ='language'),
    # path('data_ph/', pHView.as_view(),name =''),
    # path('data_clo/',CloView.as_view(),name =''),
    # path('data_tubi/', TubiView.as_view(),name =''),
]

tutorial/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from tutorial import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.login_redirest, name='login_redirest'),
    path('account/', include('accounts.urls')),
    path('manager/', include('quanly.urls')),
    path('station/',include('station.urls')),
    path('sim/', include('sim.urls')),
    path('api/', include('rest.urls')),
    path('sim/api/', include('sim.api.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

accounts/views.py
from django.contrib import messages
from django.contrib.auth.forms import (
    UserCreationForm, UserChangeForm, PasswordChangeForm )
from django.shortcuts import render, redirect
from django.http import HttpResponseForbidden,HttpResponse,HttpResponseRedirect
from accounts.form import RegisterForm, EditProfileForm
from django.views.generic import CreateView,View
from django.contrib.auth import authenticate, login, update_session_auth_hash
from accounts.models import User
from django.contrib.auth.decorators import login_required

def RegisterView(request):
    template = 'accounts/register.html'
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            if User.objects.filter(username=form.cleaned_data['username']).exists():
                return render(request, template, {
                    'form': form,
                    'alarm': 'Username đã tồn tại.'
                })
            elif User.objects.filter(email=form.cleaned_data['email']).exists():
                return render(request, template, {
                    'form': form,
                    'alarm': 'Email đã tồn tại.'
                })
            elif form.cleaned_data['password'] != form.cleaned_data['password_repeat']:
                return render(request, template, {
                    'form': form,
                    'error': 'Passwords không trùng khớp.'
                })
            else:
                User.objects.create_user(
                    username = form.cleaned_data['username'],
                    email = form.cleaned_data['email'],
                    password = form.cleaned_data['password']
                )
                return render(request, template,{
                    'user':form.cleaned_data['password'],
                    'success': 'Bạn đã đăng ký tài khoản thành công. Vui lòng liên hệ với người quản lý để tài khoản được kích hoạt'
                })

    else:
        form = RegisterForm()
    return render(request, template, {'form': form})
#
@login_required(login_url='/accounts/')
def profile_view(request):
    args = {'user': request.user}
    return render(request,'accounts/profile.html',args)

@login_required(login_url='/accounts/')
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST,instance = request.user)
        if form.is_valid():
            form.save()
            return redirect('/account/profile')
# neu sua thanh redirect('account/profile') thi url se la http://127.0.0.1:8000/account/profile/edit/account/profile
    else:
        form = EditProfileForm(instance = request.user)
        args = {'form':form}
        return render(request,'accounts/edit_profile.html',args)

@login_required(login_url='/accounts/')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('/account/profile')
            # neu sua thanh redirect('account/profile') thi url se la http://127.0.0.1:8000/account/profile/edit/account/profile
        else:
            messages.error(request, 'Please correct the error below.')

    else:
        form = PasswordChangeForm(request.user)
        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="{% static '/bootstrap/js/bootstrap.min.js' %}"></script>
    <!--Font Awesome Icons-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% block head %} {% endblock head %}
    <link rel="stylesheet" href="{% static '/accounts/style.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static '/accounts/css/login.css' %}" type="text/css">
    <link rel="icon" type="image/png" href=" {{ project.logo_company.url }}" >
    <title>{{ project.name_project }}</title>
</head>
<style type="text/css" >
#top_header{
    background:{{ project.background_top_header }};
}
#top_header div a{
    color:{{ project.color_top_header }};
}
.navbar {
    border: none;
    border-radius:0;font-weight: bold;
    background:{{ project.background_header_menu }};
}
.navbar-form {
    border: none;
}
#myNavbar ul li a {
    background:{{ project.background_header_menu }};
    color:{{ project.color_header_menu }};
}
#myNavbar ul li a:hover {
    background: #fff;
}
.panel {
    border: 1px solid {{ project.background_content_block }};
}
.panel-heading {
    vertical-align: middle;font-weight: bold;
    background:{{ project.background_content_block }};
    color:{{ project.color_content_block }};
}
.panel-body.tbl1 {
    vertical-align: middle ;
    min-height: 80px;
    line-height:80px;
    font-size: 25px;
}

.footer {
    color: {{ project.color_footer }};
    background:{{ project.background_footer }};
}

</style>
{% block css %}
{% endblock css %}
<body>
    <div class="container-fluid " id="top_header" style="">
        {% if user.is_authenticated%}
        <div style="text-align:right;margin:10px;">
            <a href="{% url 'accounts:profile_view' %}" >
                <span class="glyphicon glyphicon-user"></span> {{ user }}</a>
            <a href="{% url 'accounts:logout' %}" >
               <span class="glyphicon glyphicon-log-in"></span> Logout</a>
            <i class="fa fa-plug" style="color:#ffffff;"></i>
            <i class="fa fa-battery-full" style="color:#ffffff;"></i>
            <i class="fa fa-signal" style="color:#ffffff;"> 30</i>
            <i class="fa fa-signal" style="color:red;"> 30</i>
        </div>
        {% endif %}
    </div>
    <img id="destop" src="{{ project.image_banner.url }}">
    <nav class="navbar navbar-inverse ">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
        {% if user.is_authenticated%}
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'station:giam-sat' pk %}">Giám sát</a></li>
                <li class="active"><a href="{% url 'station:bao-cao' pk %}">Báo cáo</a></li>
                <li class="active"><a href="{% url 'station:dieu-khien' pk %}">Điều khiển</a></li>
                <li class="active"><a href="{% url 'station:ban-do' pk %}">Bản đồ</a></li>
                <li class="active"><a href="{% url 'station:canh-bao' pk %}">Cảnh báo</a></li>
                <li class="active"><a href="{% url 'station:modbus' pk %}">Modbus</a></li>
                <li class="active"><a href="{% url 'station:parameter' pk %}">Parameter</a></li>
                <li class="active"><a href="{% url 'station:suc-khoe' pk %}">Sức khỏe</a></li>
                <li class="active"><a href="{% url 'station:tai-khoan' pk %}">Tài khoản</a></li>
                <li class="active"><a href="{% url 'manager:manager' %}">Quản lý</a></li>
                <li class="active"><a href="{% url 'station:language' pk %}">Ngôn ngữ</a></li>
            </ul>
        {% endif %}
        </div>
    </nav>
<div class="container-fluid "  style="">
    <div class="row">
        <div class="col-xs-12">
            <div class="container-fluid text-center">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
        <div class="col-xs-12 text-center" style="margin-bottom:50px;">
                &copy; Bản quyền thuộc về
                <a  href="{{ project.web_company }}" target="_blank">
                {{ project.company_name }}
            </a>
        </div>
        <div class="navbar-fixed-bottom" style="background:#F57A1C;padding-top: 7px;">
            <div class="row text-center" style="vertical-align: middle;">
                <div class="col-xs-4"><a href="tel:0902555793" style="color:#fff;"><img src="http://ad.teslateq.vn/wp-content/themes/Newspaper/images/goidien.png" style="margin-bottom:10px; width:24px; height: 20px;"/> Gọi điện</a></div>
                <div class="col-xs-4"><a href="http://zalo.me/0902555793" style="color:#fff;"><img src="http://ad.teslateq.vn/wp-content/themes/Newspaper/images/zalo.png" style="margin-bottom:10px; width:24px; height: 20px;"/> Zalo</a></div>
                <div class="col-xs-4"><a href="https://teslateq.vn/contact" target="_blank" style="color:#fff;padding-right:10px"><img src="http://ad.teslateq.vn/wp-content/themes/Newspaper/images/chiduong.png" style="margin-bottom:10px; width:24px; height: 20px;"/> Liên hệ</a></div>
            </div>
        </div>
    </div>
</div>

</body>
</html>