accounts/urls.py
from django.urls import path
# from django.contrib.auth import views as auth_views
from accounts import views
# from django.contrib.auth.views import (
#     login, logout, password_reset,
#     password_reset_done,
#     password_reset_confirm,
#     password_reset_complete
# )

from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
app_name = 'accounts'
urlpatterns = [
    path('', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout', LogoutView.as_view(template_name= 'accounts/logout.html'), name='logout'),
    path('register/', views.RegisterView, name='register'),
    path('profile/',views.profile_view,name='profile_view'),
    path('profile/edit/',views.edit_profile,name='edit_profile'),
    path('change-password/', views.change_password, name='change_password'),

]

sim/urls.py
from django.urls import path
from sim import views
from sim.views import (
    SimView,
    SimListView,
    InsertControl,
    TestView,
    DeleteTestView,
    ChartView,
    DeleteTramView, ModbusView)

app_name = 'sim'

urlpatterns = [
    path('',SimView.as_view(), name ='sim'),
    path('m',ModbusView.as_view(),name = 'modbus'),
    path('sl/',SimListView.as_view(), name ='sim_list'),
    path('control/',InsertControl.as_view()),
    path('test/',TestView.as_view()),
    path('delete/test',DeleteTestView),
    path('delete/tram',DeleteTramView),
    # path('delete/tram',DeleteTramView),
    # path('chart1/',ticket_class_view),
    # path('chart', 'chartFishPrice', name='chartFishPrice'),
]

station/urls.py
from django.urls import path
from station.views import (
    StationView, ControlView, ReportView,
    MapView,HealthyView,AlarmView,
    ParameterView, ModbusView,AccountView,
    GroupView,CreateView,GroupListView,TeView,LanguageView
)
    # , ControlView, StationView ,ReportView
# from station.views.station_view import StationView
# from station.views.parameter_view import ParameterView
# from station.views.modbus_view import  ModbusView

app_name = 'station'

urlpatterns = [
    path('<int:pk>/giam-sat/', StationView.as_view(),name ='giam-sat'),
    path('<int:pk>/bao-cao/',ReportView.as_view(),name ='bao-cao'),
    path('<int:pk>/dieu-khien/',ControlView.as_view(),name ='dieu-khien'),
    path('<int:pk>/ban-do/',MapView.as_view(),name ='ban-do'),
    path('<int:pk>/suc-khoe/',HealthyView.as_view(),name ='suc-khoe'),
    path('<int:pk>/canh-bao/',AlarmView.as_view(),name ='canh-bao'),
    path('<int:pk>/parameter/',ParameterView.as_view(),name ='parameter'),
    path('<int:pk>/modbus/', ModbusView.as_view(),name ='modbus'),
    path('<int:pk>/account/', AccountView.as_view(),name ='tai-khoan'),
    path('<int:pk>/account/group/', GroupView.as_view(),name ='group'),
    path('<int:pk>/account/group/list', GroupListView.as_view(),name ='group-list'),
    path('<int:pk>/account/create/', CreateView.as_view(),name ='create'),
    path('<int:pk>/language/', LanguageView.as_view(),name ='language'),
    # path('data_ph/', pHView.as_view(),name =''),
    # path('data_clo/',CloView.as_view(),name =''),
    # path('data_tubi/', TubiView.as_view(),name =''),
]

tutorial/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from tutorial import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.login_redirest, name='login_redirest'),
    path('account/', include('accounts.urls')),
    path('manager/', include('quanly.urls')),
    path('station/',include('station.urls')),
    path('sim/', include('sim.urls')),
    path('api/', include('rest.urls')),
    path('sim/api/', include('sim.api.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

sim/models.py
import datetime
from django.db import models
from django.utils import timezone

from accounts.models import User

class Station(models.Model):
    display_name = models.CharField(max_length=50)
    symbol_name = models.CharField(max_length=50)
    serial = models.IntegerField()
    managed_by_users = models.ManyToManyField(User)
    def __str__(self):
        return self.display_name

class StationConfig(models.Model):
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    display_name = models.CharField(max_length=20)
    symbol_name = models.CharField(max_length=20)
    unit = models.CharField(max_length=10)
    def __str__(self):
        return '%s - %s - %s' % (self.station, self.symbol_name, self.unit)


class StationConfigValue(models.Model):
    station_config = models.ForeignKey(StationConfig, on_delete=models.CASCADE)
    value = models.FloatField()
    ngaygio = models.DateTimeField(auto_now_add=True, blank=True)

    def station(self):
        return self.station_config.station

    def ngaygio_ict(self):
        format = self.ngaygio + datetime.timedelta(hours=7)
        format = format.strftime("%H:%M:%S  %d-%m-%Y ")
        return format

    def ngaygio_int(self):
        format = self.ngaygio + datetime.timedelta(hours=7)
        format = format.timestamp()
        return format

class StationHealthy(models.Model):
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    display_name = models.CharField(max_length=20)
    symbol_name = models.CharField(max_length=20)
    unit = models.CharField(max_length=10)
    def __str__(self):
        return '%s - %s - %s' % (self.station, self.symbol_name, self.unit)

class StationHealthyValue(models.Model):
    station_healthy = models.ForeignKey(StationHealthy, on_delete=models.CASCADE)
    value = models.FloatField()
    ngaygio = models.DateTimeField(auto_now_add=True, blank=True)

    def station(self):
        return self.station_healthy.station

    def ngaygio_ict(self):
        format = self.ngaygio + datetime.timedelta(hours=7)
        format = format.strftime("%H:%M:%S  %d-%m-%Y ")
        return format

class Control(models.Model):
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    r1 = models.BooleanField()
    r2 = models.BooleanField()
    r3 = models.BooleanField()
    r4 = models.BooleanField()
    s1 = models.BooleanField()
    s2 = models.BooleanField()
    s3 = models.BooleanField()
    s4 = models.BooleanField()
    ngaygio = models.DateTimeField(auto_now_add=True, blank=True)

    def ngaygio_ict(self):
        format = self.ngaygio + datetime.timedelta(hours=7)
        format = format.strftime("%H:%M:%S  %d-%m-%Y ")
        return format

class Modbus(models.Model):
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    BAUD_CHOICES = (
        ('0', '4800'),
        ('1', '9600'),
        ('2', '14400'),
        ('3', '19200'),
        ('4', '28800'),
        ('5', '38400'),
        ('6', '56000'),
        ('7', '57600'),
        ('8', '115200'),
        ('9', '128000'),
        ('A', '256000'),
    )
    baud_main = models.CharField(max_length=1,choices=BAUD_CHOICES,default='9')
    address_main = models.CharField(max_length=2)
    baud_subordinate = models.CharField(max_length=1,choices=BAUD_CHOICES,default='9')
    address_subordinate = models.CharField(max_length=2)
    address_resgiter_main = models.CharField(max_length=4)
    length_resgiter_main = models.CharField(max_length=4)
    upd = models.BooleanField(default=0)
    ngaygio = models.DateTimeField(auto_now_add=True, blank=True)


class Parameter(models.Model):
    TYPE_CHOICES = (
        ('2', 'Int'),
        ('4', 'Float'),
    )
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    display_name = models.CharField(max_length=50)
    symbol_name = models.CharField(max_length=20)
    start_address = models.IntegerField()
    type = models.CharField(max_length=1,choices=TYPE_CHOICES,default='2')
    scale = models.FloatField()
    unit = models.CharField(max_length=20)

class Status(models.Model):
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    sig = models.IntegerField()
    temp = models.FloatField()
    vol = models.FloatField()
    cnn = models.BooleanField()
    b = models.IntegerField()
    n = models.BooleanField()
    d = models.BooleanField()
    ngaygio = models.DateTimeField(auto_now_add=True, blank=True)
    def ngaygio_ict(self):
        format = self.ngaygio + datetime.timedelta(hours=7)
        format = format.strftime("%H:%M:%S  %d-%m-%Y ")
        return format

class DailyRest(models.Model):
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    dr = models.IntegerField()
    ngaygio = models.DateTimeField(auto_now_add=True, blank=True)
    def ngaygio_ict(self):
        format = self.ngaygio + datetime.timedelta(hours=7)
        format = format.strftime("%H:%M:%S  %d-%m-%Y ")
        return format

class CNE(models.Model):
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    cne = models.IntegerField()
    ngaygio = models.DateTimeField(auto_now_add=True, blank=True)
    def ngaygio_ict(self):
        format = self.ngaygio + datetime.timedelta(hours=7)
        format = format.strftime("%H:%M:%S  %d-%m-%Y ")
        return format

class GPRS(models.Model):
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    gprs = models.IntegerField()
    ngaygio = models.DateTimeField(auto_now_add=True, blank=True)
    def ngaygio_ict(self):
        format = self.ngaygio + datetime.timedelta(hours=7)
        format = format.strftime("%H:%M:%S  %d-%m-%Y ")
        return format

class Test(models.Model):
    test =  models.CharField(max_length=255)
    ngaygio = models.DateTimeField(auto_now_add=True, blank=True)
    def __str__(self):
        format = self.ngaygio + datetime.timedelta(hours=7)
        format = format.strftime("%H:%M:%S  %d-%m-%Y ")
        return '%s %s' % (self.test,format)

station/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.contrib import messages
from django.contrib.auth.forms import (
    UserCreationForm, UserChangeForm, PasswordChangeForm )
from django.shortcuts import render, redirect
from django.http import HttpResponseForbidden,HttpResponse,HttpResponseRedirect
from accounts.form import RegisterForm, EditProfileForm
from django.views.generic import CreateView,View
from django.contrib.auth import authenticate, login, update_session_auth_hash
from accounts.models import User
from django.contrib.auth.decorators import login_required

def RegisterView(request):
    template = 'accounts/register.html'
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            if User.objects.filter(username=form.cleaned_data['username']).exists():
                return render(request, template, {
                    'form': form,
                    'alarm': 'Username đã tồn tại.'
                })
            elif User.objects.filter(email=form.cleaned_data['email']).exists():
                return render(request, template, {
                    'form': form,
                    'alarm': 'Email đã tồn tại.'
                })
            elif form.cleaned_data['password'] != form.cleaned_data['password_repeat']:
                return render(request, template, {
                    'form': form,
                    'error': 'Passwords không trùng khớp.'
                })
            else:
                User.objects.create_user(
                    username = form.cleaned_data['username'],
                    email = form.cleaned_data['email'],
                    password = form.cleaned_data['password']
                )
                return render(request, template,{
                    'user':form.cleaned_data['password'],
                    'success': 'Bạn đã đăng ký tài khoản thành công. Vui lòng liên hệ với người quản lý để tài khoản được kích hoạt'
                })

    else:
        form = RegisterForm()
    return render(request, template, {'form': form})
#
@login_required(login_url='/accounts/')
def profile_view(request):
    args = {'user': request.user}
    return render(request,'accounts/profile.html',args)

@login_required(login_url='/accounts/')
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST,instance = request.user)
        if form.is_valid():
            form.save()
            return redirect('/account/profile')
# neu sua thanh redirect('account/profile') thi url se la http://127.0.0.1:8000/account/profile/edit/account/profile
    else:
        form = EditProfileForm(instance = request.user)
        args = {'form':form}
        return render(request,'accounts/edit_profile.html',args)

@login_required(login_url='/accounts/')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('/account/profile')
            # neu sua thanh redirect('account/profile') thi url se la http://127.0.0.1:8000/account/profile/edit/account/profile
        else:
            messages.error(request, 'Please correct the error below.')

    else:
        form = PasswordChangeForm(request.user)
        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

station/templates/station/account.html
{%  extends 'base.html' %}
{% block content %}

<div class="row">
  <div class="col-xs-12 col-sm-10 col-sm-offset-1">
    <div class="panel ">
        <div class="panel-heading">
           Danh sách tài khoản {{stations.display_name}}
        </div>
        <div class="panel-body ">
             <div class="table-responsive-sm">
                <table class="table table-hover table-sm">
                    <thead>
                      <tr>
                          <th style="text-align: center;">STT</th>
                          <th style="text-align: center;">Name</th>
                          <th style="text-align: center;">Phân quyền</th>
                          <th style="text-align: center;">Edit</th>
                          <th style="text-align: center;">Delete</th>
                      </tr>
                    </thead>
                    <tbody>
                        <tr  class="info">
                            <td>1</td>
                            <td>abc</td>
                            <td>Kỹ thuật</td>
                            <td><i class="fa fa-edit"></i></td>
                            <td><i class="fa fa-trash"></i></td>
                        </tr>
                         <tr>
                            <td>2</td>
                            <td>xyz</td>
                            <td>Quản lý</td>
                            <td><i class="fa fa-edit"></i></td>
                            <td><i class="fa fa-trash"></i></td>
                        </tr>
                    </tbody>
                </table>
            </div>
              <div class="form-group row">
                    <div class="text-center">
                      <a class="btn btn-success" href="{% url 'station:create' pk %}" role="button">Tạo tài khoản</a>
                    </div>
                </div>
        </div>
    </div>
  </div>
    <div class=" row">
      <div class="col-xs-6">
          <a class="btn btn-info" href="{% url 'station:group' pk %}" role="button">Tạo phân quyền</a>
    </div>
        <div class="col-xs-6">
          <a class="btn btn-primary" href="{% url 'station:group-list' pk %}" role="button">List group</a>
    </div>
 </div>
</div>
<script type="application/javascript">

</script>
{% endblock content %}

station/templates/station/create.html
{%  extends 'base.html' %}
{% block content %}

<div class="row">
  <div class="col-xs-12 col-sm-8 col-sm-offset-2">
    <div class="panel ">
        <div class="panel-heading">
           Thêm tài khoản {{stations.display_name}}
        </div>
        <div class="panel-body ">
            <form>
                <div class="form-group row">
                    <div class="form-group col-md-6">
                        <label>Username</label>
                        <input type="text" class="form-control" placeholder="Username">
                    </div>
                    <div class="form-group col-md-6">
                        <label>Email</label>
                        <input type="email" class="form-control" placeholder="Email">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="form-group col-md-4">
                        <label>Password</label>
                        <input type="password" class="form-control" placeholder="Password">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Password repeat</label>
                         <input type="password" class="form-control" placeholder="Password repeat">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Group</label>
                        <select class="form-control">
                            <option selected=\'selected\' value="2">Kỹ thuật</option>
                            <option  value="4">Quản lý</option>
                        </select>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="text-center">
                      <button type="submit" class="btn btn-primary">Lưu</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
  </div>
</div>
<script type="application/javascript">

</script>
{% endblock content %}

station/templates/station/report.html
{%  extends 'base.html' %}
{% block content %}

<div class="row">
  <div class="col-sm-12">
    <div class="panel ">
        <div class="panel-heading">
            Bảng thống kê chất lượng nước {{stations.display_name}}
             <div class="row">
                      <div class="col-sm-6">
                       <label>Tần xuất log data</label>
                      <select class="form-control">
                            <option selected=\'selected\' value="0" >1 phút</option>
                            <option  value="1">5 phút</option>
                            <option  value="2">10 phút</option>
                            <option  value="3">15 phút</option>
                            <option  value="4">30 phút</option>
                            <option  value="4">1 giờ</option>

                      </select>
                    </div>

                    <div class="col-sm-6">
                       <label>Chọn nhanh khoảng thời gian</label>
                       <select class="form-control">
                            <option selected=\'selected\' value="0" >1 ngày</option>
                            <option  value="1">1 tuần</option>
                            <option  value="2">1 tháng</option>
                      </select>
                    </div>

                    <div class="col-sm-6">
                        <label>Bắt đầu </label>
                        <input id="bd" type="datetime-local" class="form-control" style="color:#000"  required>
                    </div>
                    <div class="col-sm-6">
                        <label>Kết thúc</label>
                        <input id="kt" type="datetime-local" class="form-control" style="color:#000"  required>
                    </div>
                </div>
            </br>
                 <div class=" row">
                      <div class="col-xs-6">
                           <button class="btn btn-info"" type="submit">Xem trước</button>
                    </div>
                    <div class="col-xs-6">
                        <button class="btn btn-success" type="submit">Xuất excel</button>
                    </div>
                 </div>
        </div>
        <div class="panel-body ">
            <div class="table-responsive-sm">
                <table class="table table-hover table-sm">
                    <thead>
                      <tr>
                         {% for config in  station.stationconfig_set.all %}
                        <th style="text-align: center;">{{config.name}} ({{config.unit}})</th>
                          {% endfor %}
                      </tr>
                    </thead>
                    <tbody>
                    {% for config in station.stationconfig_set.all %}
                    <tr>
                        {% for value in config.stationconfigvalue_set.all %}
                        <td>{{  value.value }} </br> {{  value.ngaygio_ict }}</td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <nav aria-label="Page navigation example">
              <ul class="pagination">
                <li class="page-item">
                  <a class="page-link" href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                  </a>
                </li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                  <a class="page-link" href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                  </a>
                </li>
              </ul>
            </nav>
        </div>
    </div>
  </div>
</div>
<script type="application/javascript">
function ngaygio(para,model) {
	var thoigian = new Date(),ngaygio;
	thoigian.setDate(thoigian.getDate() + para);
	var day = thoigian.getDate();
	var month = thoigian.getMonth() + 1 ;
	var year =thoigian.getFullYear();
    var hour = thoigian.getHours();
    var minu = thoigian.getMinutes();

    if(month < 10){
        month = "0" + month;
    }
    if(day < 10){
        day = "0" + day;
    }
    if(hour < 10){
            hour = "0" + hour;
        }
    if( minu< 10){
            minu = "0" + minu;
        }
    if(model == 1)
    	ngaygio = year+"-"+month+"-"+day+"T"+hour+":"+minu;
    else
    	ngaygio = year+"-"+month+"-"+day;
    return  ngaygio;
};
<!--console.log(ngaygio(0,0));-->

$('#bd').val(ngaygio(0,1)); $('#kt').val(ngaygio(-1,1));
$('#bd').prop('max',ngaygio(0,1));
</script>
{% endblock content %}

station/templates/station/station.html
{%  extends 'base.html' %}
{% block head %}

    <!--<script type="text/javascript" src="https://code.highcharts.com/highcharts.js"></script>-->
    <!--<script type="text/javascript" src="https://code.highcharts.com/highcharts-more.js"></script>-->
    <!--<script type="text/javascript" src="https://code.highcharts.com/modules/solid-gauge.js"></script>-->
<script src="https://code.highcharts.com/stock/highstock.js"></script>
<script src="https://code.highcharts.com/stock/modules/exporting.js"></script>
<script src="https://code.highcharts.com/stock/modules/export-data.js"></script>
{% endblock head %}
{% block content %}
<style type="text/css">

</style>
<div class="row">
  {% for station in stations.stationconfig_set.all %}
  <div class="col-sm-4 ">
    <div class="panel ">
        <div class="panel-heading">{{station.display_name}} (4.4 - 6.5) {{station.unit}} {{station.station}}</div>
        <div id="{{station.id}}" class="panel-body tbl1" style="">6.36 pH</div>
        <div class="text-primary">12:12 12/12/2012</div>
    </div>
  </div>
  {% endfor %}
</div>

<div class="row">
   <div class="col-sm-12">
    <div class="panel ">
        <div class="panel-heading" style="">Trạng thái điều khiển {{stations.display_name}}</div>
        <div class="panel-body">
            <table class="table table-hover text-center">
                 <thead>
                    <tr>
                      <th class="text-center">Tên</th>
                      <th class="text-center">Trạng thái</th>
                    </tr>
                  </thead>
                <tbody>
                  <tr class="info">
                    <td>Thiết bị 1</td>
                    <td><i style="color:green" class="fa fa-circle"> Bật</i></td>
                  </tr>
                  <tr>
                    <td>Thiết bị 2</td>
                     <td><i style="color:red" class="fa fa-circle"> Tắt</i></td>
                  </tr>
                </tbody>
              </table>
        </div>
    </div>
  </div>
   <div class="col-sm-12">
    <div class="panel">
        <div class="panel-heading">Giám sát chỉ số điện năng {{stations.display_name}}</div>
        <div class="panel-body">
            <table class="table table-hover text-center">
                 <thead>
                    <tr>
                       <th class="text-center">STT</th>
                      <th class="text-center">Thông số</th>
                      <th class="text-center">Giá trị</th>
                    </tr>
                  </thead>
                <tbody>
                  <tr class="info">
                    <td>1</td>
                    <td>Điện áp</td>
                    <td>380 VAC</td>
                  </tr>
                  <tr >
                    <td>2</td>
                    <td>Dòng điện</td>
                    <td>10 A</td>
                  </tr>
                 <tr class="info">
                    <td>3</td>
                    <td>Tổng công suất</td>
                    <td>130 kwh</td>
                  </tr>
                  <tr>
                    <td>4</td>
                    <td>Hệ số công suất</td>
                    <td>0.87</td>
                  </tr>
                </tbody>
              </table>
        </div>
    </div>
  </div>
  <div class="col-sm-12">
    <div class="panel  ">
        <div class="panel-heading" >
            Bảng giá trị max - min {{stations.display_name}} </br>
            <input type="date" id="bd" style="color:#000" />
        </div>
        <div class="panel-body ">
            <table class="table table-hover text-center">
                 <thead>
                    <tr>
                      <th class="text-center"></th>
                      <th class="text-center">Max</th>
                      <th class="text-center">Min</th>
                    </tr>
                  </thead>
                <tbody>
                  <tr class="info">
                    <td>pH</td>
                      <td>
                          <div>8.5 pH</div>
                          <div class="text-primary">29:40:25 12/02/2018</div>
                      </td>
                    <td>
                        <div>4.5 pH</div>
                        <div class="text-primary">29:40:25 12/02/2018</div>
                    </td>
                  </tr>
                  <tr>
                    <td>Clo dư</td>
                    <td>
                        <div>0.09 pH</div>
                        <div class="text-primary">29:40:25 12/02/2018</div>
                    </td>
                    <td>
                        <div>0.02 pH</div>
                        <div class="text-primary">29:40:25 12/02/2018</div>
                    </td>
                  </tr>
                  <tr class="info">
                    <td>Độ đục</td>
                    <td>
                        <div>0.35 pH</div>
                        <div class="text-primary">29:40:25 12/02/2018</div>
                    </td>
                    <td>
                        <div>0.15 pH </div>
                        <div class="text-primary">29:40:25 12/02/2018</div>
                    </td>
                  </tr>

                </tbody>
              </table>
        </div>
    </div>
  </div>
  <div class="col-sm-12">
    <div class="panel">
        <div class="panel-heading">Biểu đồ theo thời gian {{stations.display_name}}

                <div class="row">
                    <div class="col-sm-6">
                        <label>Bắt đầu</label>
                        <input id="chart_bd" class="chart" type="datetime-local" style="color:#000" required>
                    </div>
                    <div class="col-sm-6">
                        <label> Kết thúc</label>
                        <input id="chart_kt" class="chart" type="datetime-local" style="color:#000" required>
                    </div>
                </div>

        </div>
        <div class="panel-body">
            <div id="container" style="height: 200px;"></div>
        </div>
    </div>
  </div>
</div>
<script type="application/javascript">
function ngaygio(para,model) {
	var thoigian = new Date(),ngaygio;
	thoigian.setDate(thoigian.getDate() + para);
	var day = thoigian.getDate();
	var month = thoigian.getMonth() + 1 ;
	var year =thoigian.getFullYear();
    var hour = thoigian.getHours();
    var minu = thoigian.getMinutes();

    if(month < 10){
        month = "0" + month;
    }
    if(day < 10){
        day = "0" + day;
    }
    if(hour < 10){
            hour = "0" + hour;
        }
    if( minu< 10){
            minu = "0" + minu;
        }
    if(model == 1)
    	ngaygio = year+"-"+month+"-"+day+"T"+hour+":"+minu;
    else
    	ngaygio = year+"-"+month+"-"+day;
    return  ngaygio;
};
<!--console.log(ngaygio(0,0));-->

$('#bd').val(ngaygio(0,0)); $('#chart_bd').val(ngaygio(-1,1));  $('#chart_kt').val(ngaygio(0,1));
$('#bd').prop('max',ngaygio(0,0));
$('#chart_kt').prop('max',ngaygio(0,1));




<!--var seriesOptions = [],-->
    <!--seriesCounter = 0,-->
    <!--names = ['MSFT', 'AAPL', 'GOOG'];-->
<!--function createChart() {-->
    <!--Highcharts.stockChart('container', {-->
        <!--rangeSelector: {-->
            <!--selected: 4-->
        <!--},-->
        <!--yAxis: {-->
            <!--labels: {-->
                <!--formatter: function () {-->
                    <!--return (this.value > 0 ? ' + ' : '') + this.value + '%';-->
                <!--}-->
            <!--},-->
            <!--plotLines: [{-->
                <!--value: 0,-->
                <!--width: 2,-->
                <!--color: 'silver'-->
            <!--}]-->
        <!--},-->

        <!--plotOptions: {-->
            <!--series: {-->
                <!--compare: 'percent',-->
                <!--showInNavigator: true-->
            <!--}-->
        <!--},-->

        <!--tooltip: {-->
            <!--pointFormat: '<span style="color:{series.color}">{series.name}</span>: <b>{point.y}</b> ({point.change}%)<br/>',-->
            <!--valueDecimals: 2,-->
            <!--split: true-->
        <!--},-->

        <!--series: seriesOptions-->
    <!--});-->
<!--}-->
<!--$.each(names, function (i, name) {-->
    <!--$.getJSON('https://www.highcharts.com/samples/data/' + name.toLowerCase() + '-c.json',    function (data) {-->
        <!--seriesOptions[i] = {-->
            <!--name: name,-->
            <!--data: data-->
        <!--};-->
        <!--seriesCounter += 1;-->
        <!--if (seriesCounter === names.length) {-->
            <!--createChart();-->
        <!--}-->
    <!--});-->
<!--});-->

</script>
{% endblock content %}